### PR TITLE
testscript: add unquote command

### LINKED ISSUE #11: proposal: txtar: ability to define txtar archives of txtar format
This currently does not work:

```
-- output.golden.txt --
-- go.mod --
module example.com/blah

-- main.go --
package main

import "fmt"

func main() {
  fmt.Println("Hello, world!")
}
```

Unsurprisingly, it results in three files, not one `output.golden.txt`

Perhaps we could use a technique similar to shell heredocs to disambiguate?

### PR DESCRIPTION
**Pull request by rogpeppe**
We add an unquote command to the standard set of commands,
because it's not that uncommon a requirement.

We add a `-quote` flag to txtar-savedir that will automatically
quote files if needed, adding an unquote command to the
comment section.

Future work could add a way of quoting arbitrary data (e.g. binary
data) but this should do for now.

Fixes #11.

### CODE REVIEW

File: testscript/doc.go [hunk 1]
```diff
@@ -166,6 +166,11 @@ The predefined commands are:
 - mkdir path...
   Create the listed directories, if they do not already exists.
 
+- unquote file...
+  Rewrite each file by replacing any leading ">" characters from
```
Comment (myitcv) [inline testscript/doc.go]: I wonder whether it's more intuitive/useful to reference the txtar package docs here. Because the method by which we quote is defined there, as is the unquote?

Comment (rogpeppe) [reply testscript/doc.go]: I'm not sure. I think it's nice if the reader of these docs (probably someone that's trying to understand a test failure) doesn't need to go another level deeper. I'll add a note though.
