### PR TITLE
testscript: add Params.RequireExplicitExec

### LINKED ISSUE #163: suggest using `exec foo` for top-level commands rather than `foo` for consistency
At https://github.com/cue-lang/cue we use test scripts for our integration tests, as well as for users providing reproducers for bugs.

There's one unfortunate inconsistency: the former use `cue`, and the latter use `exec cue`.

I initially thought that we should use `cue` everywhere, by adding a new flag to `cmd/testscript` like `-x cue`, so that a command "passes through" to executing a program from `$PATH`. Then, we would use `cue` everywhere rather than `exec cue`. However, then bug report reproducers aren't truly standalone, as one needs to remember to use the flag.

@rogpeppe suggests that we should use `exec cue` everywhere instead. This already works in today's `testscript.RunMain`, as top-level commands are put in a temporary directory and appended to `$PATH`. We simply prefer `cue` rather than `exec cue` since we're used to how it was before, where `exec cue` might fail to find the program if one hadn't run `go install` first, as we wouldn't fix up `$PATH`.

I think Roger's idea is better. It's slightly more verbose, but:
1) It's consistent everywhere - tests and standalone reproducers.
2) It keeps `exec` explicit, which is a good thing given that it's special. It uses `stdin`, sets `stdout` and `stderr`, runs as a separate process, can be run in the background, etc.

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

Fixes #163.

### CODE REVIEW

File: testscript/cmd.go [hunk 1]
```diff
@@ -48,6 +48,15 @@ var scriptCmds = map[string]func(*TestScript, bool, []string){
 	"wait":     (*TestScript).cmdWait,
 }
 
+var builtinCmds map[string]bool
```
Comment (rogpeppe) [inline testscript/cmd.go:51]: Rather than doing this, how about just putting the check into the actual command function itself? That way it'll work even if the command overrides a builtin command too.

In `exe.go`:
```
			scriptCmds[name] = func(ts *TestScript, neg bool, args []string) {
				if ts.params.RequireExplicitExec {
					ts.Fatalf("use 'exec %s' rather than '%s' (because RequireExplicitExec is enabled)", args[0], args[0])
				}
				ts.cmdExec(neg, append([]string{name}, args...))
			}
```

(also above, a mild suggestion for a phrasing change to the error message because i'm not overly keen on "as per")

File: testscript/exe.go [hunk 2]
```diff
@@ -42,11 +42,15 @@ func IgnoreMissedCoverage() {
 // code to pass to os.Exit. It's OK for a command function to
 // exit itself, but this may result in loss of coverage information.
 //
-// When Run is called, these commands will be available as
-// testscript commands; note that these commands behave like
-// commands run with the "exec" command: they set stdout
-// and stderr, and can be run in the background by passing "&"
-// as a final argument.
+// When Run is called, these commands will work when run via "exec".
```
Comment (rogpeppe) [inline testscript/exe.go:45]: I think it should explicitly say that the commands are installed in the path and are hence available as normal commands (not just via `exec`) because that might not be entirely obvious to the casual reader.

How about something like this?

```
When Run is called, these commands are installed as regular commands in the shell
path, so can be invoked with "exec" or via any other command (for example a shell script).
```

**Review by rogpeppe — COMMENTED** [review]
Thanks for doing this! LGTM in general modulo a few comments and suggestions.

File: testscript/cmd.go (hunk 1 above)
Comment (mvdan) [reply testscript/cmd.go:51]: Much cleaner, thank you!

I took this route because, in my head, builtins could not be shadowed or overriden. That's a question for a different thread, though.

File: testscript/exe.go (hunk 2 above)
Comment (mvdan) [reply testscript/exe.go:45]: Good point, that's less ambiguous.

**Comment by mvdan** [comment]
@rogpeppe ready for a final approval, I think.

**Review by rogpeppe — APPROVED** [review]
LGTM thanks!
